//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: hello.proto
//
//package com.study.rpc.demo04.proto;
//
//public interface HelloReplyOrBuilder extends
//    // @@protoc_insertion_point(interface_extends:hello.HelloReply)
//    com.google.protobuf.MessageOrBuilder {
//
//  /**
//   * <code>optional string message = 1;</code>
//   */
//  String getMessage();
//  /**
//   * <code>optional string message = 1;</code>
//   */
//  com.google.protobuf.ByteString
//      getMessageBytes();
//}
