//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: hello.proto
//
//package com.study.rpc.demo04.proto;
//
//public interface HelloRequestOrBuilder extends
//    // @@protoc_insertion_point(interface_extends:hello.HelloRequest)
//    com.google.protobuf.MessageOrBuilder {
//
//  /**
//   * <code>optional string name = 1;</code>
//   */
//  String getName();
//  /**
//   * <code>optional string name = 1;</code>
//   */
//  com.google.protobuf.ByteString
//      getNameBytes();
//}
